### ISSUE TITLE
NGUI sysfont clipped view bug

### ISSUE THREAD

**Issue by eddieKayac** [imkira/unity-sysfont#2]
I insert the sysfont in a NGUI clipped view and when i drag an item i can see the text of all the hidden item text. 
NGUI Scroll view (Panel).

http://www.hiboox.com/go/pictures/private-picture/bugsysfont,8e75d392ae2534b0b0123266ff71a8ba.png.html

**Comment by imkira** [comment]
Hello Eddie,

Can you post a screenshot of the problem so that I can better understand it?
Thanks

**Comment by eddieKayac** [comment]
There it is http://www.hiboox.com/go/pictures/private-picture/bugsysfont,8e75d392ae2534b0b0123266ff71a8ba.png.html.
i'm currently trying the other way with a camera thanks for the tools and
the quick answer.

**Comment by imkira** [comment]
Hello Eddie,

I see. I am wondering wether you are using a shader other than the "Unlit/Translarent Colored" supplied with NGUI.
If you don't mind, can you send me the unity scene file and the minimum necessary files (like the texture atlas) so that I can reproduce that problem on my machine? You can exclude NGUI and unity-sysfont related code since I already have it.

Please send it to my mail: imkira@gmail.com

I will be happy to analyze that problem for you.

**Comment by imkira** [comment]
Hello Eddie, I have checked the sample you sent me but I couldn't reproduce the problem you stated.

I basically did the following before using your package:
- Made sure I was running the latest Unity version: 3.5.3f3
- Created a new empty project
- Downloaded and imported the latest version of NGUI
- Downloaded and imported unity-sysfont
- Imported your package (I did not import NGUI/Scripts/UI/\* and NGUI/Scripts/Interaction/*)

I believe you are not running the latest version of NGUI, that is why I did not import NGUI/Scripts/UI/\* and NGUI/Scripts/Interaction/*, because when I first tried to import it it just didn't compile against my version of NGUI.

After that I  launched SceneTestNgui_ClippedView and everything looks normally clipped: item UILabel, item button and the pink description.

Can you try the steps I wrote before on your environment and confirm whether the problem still happens?

**Comment by eddieKayac** [comment]
The last version of NGUI fix the bug. 
thanks for your help.

**Comment by knighthedspi** [comment]
when i used NGUI version 2.7.0 with Unity 3.5.7f2, this bug still appeared. 
Anybody help me?
Any help will be appreciated
