### ISSUE TITLE
_context no longer works. 

### ISSUE THREAD

**Issue by stylophone** [imkira/unity-sysfont#7]
Hi, just want to let you know that "MyEAGLContext _context" is no longer exists on Unity 4.0 xcode project. Therefore that "extern EAGLContext\* _context" will cause a compiling problem. You may want to define it directly into UnitySysFontTextureManager and allocating by call _context = [EAGLContext currentContext] from inside of initWithCapacity instead..

**Comment by imkira** [comment]
Hello stylophone.

Yes! I already have a patch for that but I still haven't committed it.

**Comment by imkira** [comment]
Give me just a few days until I can properly test it properly against both Unity 3 and 4.

**Comment by groscalin** [comment]
@imkira we're waiting for the patch,,

cuz i don't know if there is any xcode define for identifying unity version number, it's accessible via the DisplayManager but it makes compile error on pre unity4 build..

so. Ganbatekudasai. :)

**Comment by imkira** [comment]
Sorry for the huge delay.

Please check out the new [development branch for Unity 4.x here](https://github.com/imkira/unity-sysfont/tree/unity4x).
If you have the latest NGUI you might also want to download the latest version from the link above.

Let me know if it works for you too.

**Comment by stylophone** [comment]
Thanks for the fix. It works well under my Unity 4.1.2! And about the way to spot Unity 3, since the -(void) startRendering; method is abrogated from AppController.h in Unity4 project, maybe something like:

#import "AppController.h"

AppController _appDelegate = (AppController_)[[UIApplication sharedApplication] delegate];

if ([appDelegate respondsToSelector: @selector(startRendering)])
{
    NSLog(@"Unity 3.x");
}
else
{
    NSLog(@"Unity 4.x");
}

could do that job. Haven't tested yet :)

**Comment by imkira** [comment]
@stylophone, I thought of doing it like you said by using reflection but that won't work nicely because it will still fail during the linking since it cannot find the "extern" I am defining for `_context`.

In order to do it that way I would need to remove the extern declaration of the `_context` symbol and get its value somehow via reflection / pointer hacking.
A much easier way would be to handle it in the preprocessor by using `#ifdef`. It is possible since AppController.h, Gles_Common.h etc both exist in the projects exported by Unity3 and Unity4 and there are defines that exist in one version but not in the other and vice-versa. I initially thought of this, since it would alleviate the pain of maintaining the whole thing. The reason I decided to create a new branch was simply to free the maintenance of this project from #ifdef stuff that can work well on iOS now but may not work well on Android.jar/MacOSX.bundle tomorrow (so I will still need to make 2 packages for each since those are precompiled binaries).
